### ISSUE TITLE
timewheel

### ISSUE THREAD

**Issue by CCwantspizza** [DemonsLu/game-toolkit#3]
when calculating new timerId on line153,should it be something like this:
    targetIndex := wheel.CurIndex + int(offset) 
since int(offset) < slotlen,no need to offset mod slotLen

**Comment by DemonsLu** [comment]
Thanks for your issue, I will change this soon.

**Comment by DemonsLu** [comment]
@CCwantspizza Done, see b931dd1aa1f3721a884737843bbc2cb016f93cd5
